name: "Update Readme"

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/tpl/*'
      - '.github/data/*'
      - '.github/workflows/readme.yml'

  release:
    types: [ published ]
    
    
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Get latest release
        id: get-latest-release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(gh api "repos/${{ github.repository }}/releases/latest" --jq .tag_name)
          echo "tag_name=$tag" >> $GITHUB_OUTPUT

      - name: Using main branch
        run: |
          git switch main || (git fetch --all && git checkout -b main origin/main)
          echo "LATEST_MAJOR=$(echo ${{ steps.get-latest-release.outputs.tag_name }} | cut -d . -f 1)" >> $GITHUB_ENV
          echo "LATEST_TAG=${{ steps.get-latest-release.outputs.tag_name }}" >> $GITHUB_ENV
          latest=$(ls conf/*.conf | tail -1)
          echo "LATEST_CONF=$latest" >> $GITHUB_ENV

      - name: Update the readme.md
        uses: anyvm-org/template-render@v0.0.2
        with:
          datafile: .github/data/datafile.ini
          files: |
            .github/tpl/README.tpl.md : README.md

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update version to ${{ steps.get-latest-release.outputs.tag_name }}"
          pull: '--rebase --autostash '
          add: |
            README.md

